### ISSUE TITLE
Autoplot with survfit object ≠ autoplot with ten object

### ISSUE THREAD

**Issue by waltonjones** [dardisco/survMisc#10]
For some reason these plots look completely different.

What could make the survfit plot go to zero and the other not make it to zero?

# survfit
![survfit](http://files.joneslab.org/1i2YW/4tAfc6EI+)

# ten
![ten](http://files.joneslab.org/1a8xu/3EtYP0Ac+)

**Comment by waltonjones** [comment]
I tracked this in a difference in the way Survivorship (S) is being calculated by the survival package. In the survMisc autoplot.ten function, you are using the ci function to calculate survivorship. It does not seem to go down to zero, while the function doing the same thing in the survival package does.

**Comment by waltonjones** [comment]
Here is the dataset used to produce the above curves:

http://files.joneslab.org/15oPW/gwvzMHZy

I used dput() to export it to a plain text file.

**Comment by dardisco** [comment]
Got it. It's a typo in 
survMisc:::sf.ten
res1[, `:=`((what), x[which(t %in% res1$t), fun1(e, n), by = eval(cg)]$V1)]
should read
res1[, `:=`((what), x[which(t %in% res1$t), fun1(e, ncg), by = eval(cg)]$V1)]
Fixed on github; will fix on release 0.5.3 on CRAN, will try to get this up next week.
